title: Sixth Server
description: A Forth HTTP/JSON server framework compiled to native ARM64 binaries
remote_theme: just-the-docs/just-the-docs

url: "https://quivent.github.io"
baseurl: "/sixth-server"

permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock

aux_links:
  "GitHub":
    - "https://github.com/quivent/sixth-server"

color_scheme: dark

search_enabled: true

heading_anchors: true
